x=[0:0.01:1];
y=[0:0.01:1];
[u,v]=meshgrid(x,y);
A=2;
B=1;
S=2;
m1 = 2 - exp(cos(A.*power(u, B).*pi)+0.5.*(cos(A.*power(u, B).*pi)-0.5).^4)./(power(2, S).* A);
m2 = 2 - exp(cos(A.*power(v, B).*pi)+0.5.*(cos(A.*power(v, B).*pi)-0.5).^4)./(power(2, S).* A);
ma=(m1.*m2)./2;
m= ma;
f1=m.*(1-cos(u.*pi./2)).*(1-cos(v.*pi./2));
f2=m.*(1-cos(u.*pi./2)).*(1-sin(v.*pi./2));
f3=m.*(1-sin(u.*pi./2));
mesh(f1,f2,f3);
alpha(0);
hold on;
data = load('C:\Users\lurso\Desktop\PlatEMO\PlatEMO v1.5 (2017-12)\Problems\XPMOP\trueKnee\PMOP9-3.mat');
A = data.Objs;
f1=A(:,1);
f2=A(:,2);
f3=A(:,3);
plot3(f1,f2,f3,'MarkerSize',12, 'Marker','p','LineStyle','none','LineWidth',1, 'Color',[1 0 0]);
hold on;
% A = load('C:\Users\lurso\Desktop\Angle-dominance\exp\with_linkage\ExpKnee\KDMOEA+\PMOP9-3\2.txt');
% A = load('C:\Users\lurso\Desktop\Angle-dominance\exp\with_linkage\ExpKnee\NSGA2+Dis\PMOP9-3\17.txt');
% A = load('C:\Users\lurso\Desktop\Angle-dominance\exp\with_linkage\ExpKnee\NSGA2+EMU\PMOP9-3\2.txt');
% A = load('C:\Users\lurso\Desktop\Angle-dominance\exp\with_linkage\ExpKnee\NSGA2+WD\PMOP9-3\2.txt');
% A = load('C:\Users\lurso\Desktop\Angle-dominance\exp\with_linkage\ExpKnee\RVEA+Dis\PMOP9-3\19.txt');
% A = load('C:\Users\lurso\Desktop\Angle-dominance\exp\with_linkage\ExpKnee\RVEA+EMU\PMOP9-3\8.txt');
A = load('C:\Users\lurso\Desktop\Angle-dominance\exp\with_linkage\ExpKnee\RVEA+WD\PMOP9-3\1.txt');

f1=A(:,1);
f2=A(:,2);
f3=A(:,3);
plot3(f1,f2,f3,'MarkerSize',8, 'Marker','o','LineStyle','none','LineWidth',1, 'Color',[0 0 1]);
view(59,48);
legend('PoF','Knee point','Solution','Location','northeast');
xlabel('$\it{f_1}$','Interpreter','latex','FontName','Arial Italic');
ylabel('$\it{f_2}$','Interpreter','latex','FontName','Arial Italic');
zlabel('$\it{f_3}$','Interpreter','latex','FontName','Arial Italic');
set(gca,'FontSize',20);