clc;
clear all;
% x=[0:0.01:1];
% y=[0:0.01:1];
% [u,v]=meshgrid(x,y);
% A=2;
% B=1;
% S=-2;
% m1 = 5+10.*(u-0.5)*(u-0.5) + cos(A.*pi.*power(u,B))./(A.*power(2,S)); 
% m=sqrt(m1);
% f1=m.*u.*v;
% f2=m.*u.*(1-v);
% f3=m.*(1-u);
% mesh(f1,f2,f3);
% hold on;
data = load('C:\Users\lurso\Desktop\PlatEMO\PlatEMO v1.5 (2017-12)\Problems\XPMOP\trueKnee\PMOP13-5.mat');
A = data.Objs;
f1=A(:,1);
f2=A(:,2);
f3=A(:,3);
plot3(f1,f2,f3,'MarkerSize',12, 'Marker','p','LineStyle','none','LineWidth',1, 'Color',[1 0 0]);
hold on;
hold on;
A = load('C:\Users\lurso\Desktop\Angle-dominance\exp\with_linkage\ExpKnee\KDMOEA+\PMOP13-5\6.txt');
% A = load('C:\Users\lurso\Desktop\Angle-dominance\exp\with_linkage\ExpKnee\NSGA2+Dis\PMOP13-3\17.txt');
% A = load('C:\Users\lurso\Desktop\Angle-dominance\exp\with_linkage\ExpKnee\NSGA2+EMU\PMOP13-3\2.txt');
% A = load('C:\Users\lurso\Desktop\Angle-dominance\exp\with_linkage\ExpKnee\NSGA2+WD\PMOP13-3\2.txt');
% A = load('C:\Users\lurso\Desktop\Angle-dominance\exp\with_linkage\ExpKnee\RVEA+Dis\PMOP13-3\19.txt');
% A = load('C:\Users\lurso\Desktop\Angle-dominance\exp\with_linkage\ExpKnee\RVEA+EMU\PMOP13-3\8.txt');
% A = load('C:\Users\lurso\Desktop\Angle-dominance\exp\with_linkage\ExpKnee\RVEA+WD\PMOP13-3\1.txt');
f1=A(:,1);
f2=A(:,2);
f3=A(:,3);
plot3(f1,f2,f3,'MarkerSize',8, 'Marker','o','LineStyle','none','LineWidth',1, 'Color',[0 0 1]);
% legend('PoF','Knee point','Solution','Location','northeast');
xlabel('$\it{f_1}$','Interpreter','latex','FontName','Arial Italic');
ylabel('$\it{f_2}$','Interpreter','latex','FontName','Arial Italic');
zlabel('$\it{f_3}$','Interpreter','latex','FontName','Arial Italic');
set(gca,'FontSize',20);
view(68,15);